name: Expression implementation
on: push
env: 
  appName: CounterApp
jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: Execute command
        run: echo "Build automation for application cualquiera"
