name: Expressions implementation
on: push
env:
  appName: CounterApp

jobs:
  build_job:
    runs-on: windows-latest
    steps:
      - name: Cache
        uses: actions/cache@v1.2.1
        with:
          # A directory to store and save the cache
          path: "C:\Users\rplazag\Documents\github"
          key: "micache"
          # An ordered list of keys to use for restoring the cache if no cache  hit ocurred for key
          restore-keys: ""          
      - name: Execute Command
        run: echo "Build Automation for Application: CounterApp"
