name: Docker image Build Process
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      access-token:
        description: 'A token passed from the caller workflow'
        required: false
  #push:
jobs:
  docker:
    env:
      appName: "spring-boot-image"
    runs-on: ubuntu-latest
    steps:
      
      - name: get username
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}"
      - name: Login with credentials to my account Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAM }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
