name: Docker image Build Process
on:
  #workflow_dispatch:
  #workflow_call:
  push:
jobs:
  env:
    name: "spring-boot-image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login with credentials to my account Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAM }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push the application
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAM }}/${{ env.name }}:latest
 
        
