name: Docker image Build Process
on:
  #workflow_dispatch:
  #workflow_call:
  push:
jobs:
  env:
    appName: "spring-boot-image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
 
        
