name: Java CI with Maven
on:
  push:
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  maven_build:
    strategy:
      matrix:
        version: [11,8]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK "${{ matrix.version }}"
        uses: actions/setup-java@v3
        with:
          java-version: "${{ matrix.version }}"
          distribution: 'temurin'
          cache: maven
          
